### ISSUE TITLE
Support GUI Actions for Write Operations in Frontend

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1061]
#### Description:
We need to support GUI actions for write operations (POST, PUT, PATCH, DELETE) in the frontend. This requires proper handling of state-changing HTTP methods and integration with an existing service provider endpoint developed by the backend team. 

Read (GET) operation is already supported, and write actions is partially supported, but not tested.

#### Task Details:
1. **Frontend Integration**:
   - Ensure the frontend handles `POST`, `PUT`, `PATCH`, and `DELETE` methods via fetch requests. 
   - Pass the `Authorization` token (`dialogToken`) in the request headers.
   - Handle responses for success and error scenarios (e.g., status codes, errors).
   - Ensure UI feedback is provided after state changes (e.g., success, error messages).

Should `POST` be supported as a form, and not a fetch with payload?

2. **Testing**:
   - Verify that GUI actions work correctly with the existing service provider endpoint.
   - Test various scenarios including successful writes and error handling.

#### Acceptance Criteria:
- [ ] GUI actions for `POST`, `PUT`, `PATCH`, and `DELETE` are fully functional in the frontend.
- [ ] The frontend communicates with the backend service provider endpoint using the correct HTTP methods.
- [ ] Proper error handling and UI feedback is implemented for all actions.

This task focuses solely on ensuring the frontend supports write actions via existing backend endpoints.

**Comment by alexdigdir** [comment]
Ref.: https://github.com/Altinn/dialogporten-serviceprovider

**Comment by LeifHelstad** [comment]
## Test

Eksempel fra GUI 

<img width="1021" alt="Image" src="https://github.com/user-attachments/assets/08d42cc2-4510-4f91-ba8a-f071a86d06b7" />

**Comment by LeifHelstad** [comment]
## Testreport

GUI actions for POST, PUT, PATCH, and DELETE are fully functional in the frontend.
* POST og DELETE er testet
* Disse gjør begge kall med forventet resultat til https://github.com/Altinn/dialogporten-serviceprovider?tab=readme-ov-file#dialogporten-service-provider
* Desverre er ikke test service providern satt opp til å oppdatere dialogporten i Staging miljøet. Men den oppdateringen er ikke en del av testingen her, kun en tilleggsobservasjon

The frontend communicates with the backend service provider endpoint using the correct HTTP methods.
* Som nevnt i forrige punkt er kommunikasjonen OK. Response, Request og Headers er inspisert via Devtools (Fn+F12) underveis i testen og gir forventet resultat.

Proper error handling and UI feedback is implemented for all actions.
* Ved å angi en felaktig URL oppnår ikke bakgrunnsjobben kontakt med server. 
  - Bruker blir ikke oppdatert om feilen
  - Løsningen takler at dette feiler

**Comment by LeifHelstad** [comment]
## Miljøoppdatering

Siden det nå er Staging det testes mest fra er test-komponenten nå skrudd om til å oppdatere dialoger i "Staging" og ikke "Test"

<img width="574" alt="Image" src="https://github.com/user-attachments/assets/412c09a8-6de1-4658-bc72-3cb632d63b04" />
