### ISSUE TITLE
Select party: Group all organization as a single option

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1071]
**Functionality**
Add support for selecting "all organizations" in the Partylist (used in global menu and in PartyDropdown).

**Motivation**
In order to achieve functionality and actively take advantage of searching and listing dialogs across parties. This is a quick win and can serve not only as a temporary solution, but align with a future vision. 

**Specs**

- "all organizations" should be represented with a list of combined avatars
- Due to API restrictions, there should be a limit of how many organizations should be included (max 20 organizations? Make it configurable) 
- Grouping of parties should be:
  
    > End USER
     _________
    > PERSON 1
    > PERSON 2
   .....
   __________
  > organization 1
  > organization 2
 ... 
 > all organization

- Parties with  subparties with same name should be merged
- All organizations" is only viable when there are at least two organizations
- No boundary for how many organization can be grouped by "all organizations". Note: There should be  limited due to  API limitations.
- 
**testing**

provide unit tests describing the scenarios and storybook examples to problematize the needs

![Image](https://github.com/user-attachments/assets/1c55d9cd-74ad-4d2f-a3f7-995e1b4e1ea5)

```[tasklist]
### Tasks
- [x] Add all organizations to partylist
- [x] Refactor partylist to be data agnostic
- [x] Support for overflowing and fix layout issues in global menu
- [ ] Create AvatarGroup
```
