### ISSUE TITLE
Explore design concepts for dialogs

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#111]
Explore how dialogs work with different content, during different states, in different contexts, including:

```[tasklist]
### Letters
- [x] Unread (new letters)
- [x] Read (by whom?)
- [ ] Confidential letters
- [x] Read confirmation
```

```[tasklist]
### Tasks (forms)
- [x] Sent to user
- [x] Created by user
- [x] Work-in-progress
- [x] Waiting for response
- [x] Completed
```

```[tasklist]
### Context
- [x] Inbox, Archive, Deleted
- [x] Search
- [x] Collapsed view
- [x] Expanded view
- [x] Desktop
- [x] Mobile
```

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/b453eb0c-9e23-4e82-8eb9-4eabb6833d3f)

Todays collapsed view examined.

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/30912db6-dafc-4648-8850-54703f788bba)

Draft of new list element explained.

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/82095cd4-033e-4cf1-98da-af6c2a3e77df)

New form, in progress, complete.

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/aa551fe7-d24a-47ae-a954-7dd6b0cd62f4)

New form with due date.

**Comment by ingefossland** [comment]
![image](https://github.com/digdir/dialogporten-frontend/assets/1138656/3672bed7-9430-4077-bf7f-f92ee04fabd7)

Unread, read, hover and selected state.

**Comment by indiamaydesign** [comment]
#174 will be tackling read information moving forward. Confidential letters is slightly out of scope for now but can be revisited later on.

**Comment by indiamaydesign** [comment]
#174 will be tackling read information moving forward. Confidential letters is slightly out of scope for now but can be revisited later on.
