### ISSUE TITLE
Define concept - part A (minimum solution)

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#13]
### **Beskrivelse**
Lande et løsningskonsept - del A (minimumsløsning) som tas videre I prosessen 
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/88
- [ ] Conduct WS to create vision, goals and concept for the mvp of the new inbox
- [x] Coordinate prioritized user needs with tech to understand the possibilties
- [x] Create hypothesis
- [x] Summerize the key findings from research into functionality to form the outline of the solution
```

**Comment by indiamaydesign** [comment]
@sorensensig is the workshop for task 2 here the same as the workshop we had pre-OKRs the other day or something else we should hold?

**Comment by indiamaydesign** [comment]
@Hamyng @ingefossland @AudunFK wanted to get your eyes on this one - especially point 2 - we can touch base about this when we next meet in person to see how we are feeling re: vision, mission etc

**Comment by indiamaydesign** [comment]
Initial concept for user testing defined, with further iteration and changes ongoing
