### ISSUE TITLE
Improving search

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#142]
## Issues

- Large inboxes will not display any results due to technical issues, forcing the user to search
- But today's search doesn't give exptected results.
- Only titles are indexed, leading to producers creating long and unfriendy titles
- Searching for senders name will not give any resuits
- Searching for content other than titles will not give any results
- Searching for content in attachments will not give any results
- Another issue is that many dialogs have incomplete or no content at all
- Searching by status, date, etc uses pre-filtering and might lead to zero results.

## Hypothesis
- Search should use dictionaries, rules, and machine learning to detect and correct misspelt words.
- Search results should include content from all parts of Altinn (dialogs, people, organizations, information, help resources etc).
- Search results should indicate hits from other actors than the current.
- Search results should be ordered by priority according to user needs/relevance. 
- Users should be able to order and sort results depending on preference.
- Search words should be highlighted in results.
- Pre-filtering is not a user friendly pattern. Advanced needs can be handled using post filtering and suggestions.
- In addition to exact results based on user queries, the search should suggest relevant options (other queries, relevant filters, popular results, help, etc.)

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/307
- [ ] https://github.com/digdir/dialogporten-frontend/issues/143
- [ ] https://github.com/digdir/dialogporten-frontend/issues/404
- [ ] https://github.com/digdir/dialogporten-frontend/issues/394
```

### Oversikt
Epicen omhandler design av funksjonalitet i innboksen/arkivet/skjema som bidrar til å øke kvaliteten på søkeresultater, funksjonalitet i søkefeltet og søkeresultater. Epicen omhandler også funksjonalitet som lagrede søk og administrasjon av dine lagrede søk. 

### Tidligere hypoteser:
- [x] Ved å utbedre søk til å tilrettelegge for feilstavelser og synonymer vil vi gi brukeren bedre tilgang på informasjon i innboksen
- [ ] Ved å kombinere filtre og konvertere de til lagrede søk, forventer vi å erstatte behovet for å gi lagrede søk unike egne navn. Dette kan forenkle brukerens håndtering av lagrede søk og organiseringen av søkefunksjonaliteten.
- [x] Ved å la innbyggere søke i alt innhold, ikke bare tittel, forventer vi bedre treff og mer relevante resultater. Dette antas å forbedre søkeopplevelsen.
- [ ]  Ved å gi brukeren muligheten til å lagre søk som en del av selve søkeprosessen, forventer vi at det blir lettere å lage de
- [x] Ved å fremheve brukerens søkeord i resultater, forventer vi at det blir tydeligere hva du har søkt på og fremhever relevante treff. Vi tror dette vil øke relevansen av søkefunksjonen i innboksen.
- [ ] Ved å bedre tilgangen og prosessen for å søke på tvers av aktører i innboksen, forventer vi å gi innbyggere muligheten til å få oversikt over dialoger på tvers av innbokser for flere aktører. Dette grepet forventer vi at vil gjøre det lettere for brukere å holde oversikt over frister/skjema på tvers av aktører.

**Avkryssede elementer er verifiserte hypoteser.**

### Oppgaver
Liste over alle oppgavene som må fullføres i epicen. 

[Oppgaveliste]
- [ ] Link til oppgave
- [ ] Lag en oppgave som ikke trenger en issue 
- [ ] Lag en oppgave og gjør den om til en issue 

### Definition of done
Denne epicen avsluttes når alle hypotesene er verifisert/avkreftet og elementer av søk er fullført og validert

**Comment by MetteSaltnes** [comment]
Denne er duplikat av denne: https://github.com/digdir/dialogporten-frontend/issues/1449 
Hvem lukkes, eventuelt innhold som bør flyttes over?

**Comment by AudunFK** [comment]
Denne gikk inn i en ryddejobb jeg og Kim gjorde forrige uke, den er erstattet av Fungerende søk
[#1449](https://github.com/digdir/dialogporten-frontend/issues/1449)
