### ISSUE TITLE
Explore list view functionality

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#145]
### Hypoteser:
- [ ] Ved å inkludere progresjonsindikatorer for oppgaver, ønsker vi at brukerne enklere klarer å skille oppgaver fra meldinger, samt forstå fremdrift i en konkret oppgave.
- [x] - Ved å erstatte ikoner for å representere en type dialog (melding, til utfylling) med metadata, forventer vi å forenkle grensesnittet og samtidig gi mer beskrivende informasjon om dialogens status.
- [ ] - Ved å vise når dialogen sist er oppdatert og hvem som har jobbet med oppgaven sist, forventer vi å gi brukerne bedre innsikt i dialoghistorikken og ansvarsfordelingen. Dette antas å øke transparensen og samarbeid i altinn innboksen.
- [ ] - Ved å tydeliggjøre farger og fargens betydning på dialoger sin status, forventer vi å gi brukere umiddelbar informasjon om sakenes status. Dette grepet skal hjelpe brukeren forstå hva som er viktig
- [ ] - Ved å gi muligheten til å tildele et dialogelement med en ansvarsperson direkte i innboksen, forventer vi at brukerene vil oppleve større grad av kontroll og gi bedre oppgaveadministrasjon.
- [x] - Ved å endre det gamle interaksjons mønsteret i innboksen (med collapse/expand) til egne sider per dialog forventer vi at brukerne vil finne det lettere å fokusere på en dialog om gangen. Dette designvalget antas å forbedre brukerens konsentrasjon og muligheten til å bygge på dialoger gradvis iht utviklinge av dialogporten og funksjonaliten.
- [x] - Ved å plassere fast funksjonalitet som sletting, arkivering, videresending, og flytting visuelt bort fra individuelle dialoger og ned på en oppgavelinje, forventer vi at brukerne vil oppleve bedre tilgjengelighet og enklere navigasjon.
- [x] Ved å bruke farger for å vise forskjellen mellom uleste og leste meldinger, forventer vi at brukerne vil kunne skille mellom ny og behandlet informasjon raskt. Dette designvalget antas å forbedre brukerens oppmerksomhet.

### Sekundære Hypoteser
- Ved å indikere svarfrist og godkjente/avviste vedtak med farger, forventer vi å tydeliggjøre viktig informasjon. Denne fargekodingen antas å forbedre brukerens forståelse av dialogens status

**Avkryssede elementer er verifiserte hypoteser.**
 
### Oversikt
Epicen omhandler redesign av listevisningen av meldinger og oppgaver som brukerene ser når de benytter Altinn innboks. Formålet med ep

### Oppgaver
Liste over alle oppgavene som må fullføres i epicen. 

[Oppgaveliste]
- [ ] Link til oppgave
- [ ] Lag en oppgave som ikke trenger en issue 
- [ ] Lag en oppgave og gjør den om til en issue 

### Definition of done
Denne epicen avsluttes når alle hypotesene er verifisert/avkreftet og listevisningen er fullført klar til implementasjon.
