### ISSUE TITLE
Clarify units, subunits and private inboxes

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#146]
## Issues
- Users with many actors have issues with identifying which one is active
- Subunits are not obvious, leading to dialogs being ignored
- Color themes and icons representing company and user is too subtle
- Users experience of the difference between actors is unclear

## Hypothesis
- Using avatars for companies and user is a well-known pattern that can improve recognition.
- Colour themes (company vs person) can be continued but must be clearer
- Individual colour themes per actor might help users identify favourites
- Actor choice can be simplified by combining main unit and subunits.
- Subunits can be accessed using filters.

**Avkryssede elementer er verifiserte hypoteser.**
```[tasklist]
### Tasks
- [ ] Explore concept for avatars and color theming
- [ ] https://github.com/digdir/dialogporten-frontend/issues/405
- [ ] https://github.com/digdir/dialogporten-frontend/issues/325
```
