### ISSUE TITLE
Explore task management

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#174]
🔗 to Figjam file to come

### Oversikt: 
Epicen omhandler design av funksjonalitet i innboksen som gir brukeren kontroll over oppgavebehandling. Arbeidet vil utfordre noen elementer av etablerte arbeidsflyter. Fokus vil være på hyppige tester mot flere nøkkelsegmenter i dagens innboksløsning. 

### Hypotese 

- [ ] Ved å inkludere progresjonsindikatorer for oppgaver, ønsker vi at brukerne enkleree klarer å skille oppgaver fra meldinger, samt forstå fremdrift i en konkret oppgave.
- [ ] Ved å legge til avatar/ikon fra avsenderen tror vi at brukerne enklere vil forstå hvilken etat/organisasjons som har sendt dialogen/oppgaven. Dette designvalget antas å øke klarheten rundt ansvar og aktører.
- [ ] Ved å gi muligheten til å tildele et dialogelement med en ansvarsperson direkte i innboksen, forventer vi at brukerene vil oppleve større grad av kontroll og gi bedre oppgaveadministrasjon.
- [ ] Ved å la brukere sette opp sin egen mappestruktur i innboksen, er tanken å tilføre en ny form for kontroll for brukerne. Dette designvalget antas å forbedre organiseringen og tilgjengeligheten av innhold.
- [ ] Ved å implementere funksjonalitet for å pinne/lable/tagge dialoger, forventer vi å gi brukerne økt kontroll over sin innboks. Denne tilpasningen antas å lette brukernes administrasjon av viktige meldinger/oppgaver å benytte gjenkjennbare elementer fra andre innbokser.
- [x] Ved å legge til navigasjon for innkommende «meldinger», «utkast», og «sendt» i menyelementer, forventer vi at brukerne vil oppleve en mer intuitiv og effektiv innboks som gir et oversiktlig bildet knyttet til oppgaveadministrasjon og status.
- [ ] Ved å rendyrke arkivet og slettet som mapper som brukeren selv administrerer, forventer vi å unngå forvirring ved at enkelte oppgaver blir automatisk arkivert. Klar og tydelig brukeradministrasjon av arkiverte dialoger og slettede elementer antas å forbedre brukerens/organisasjonens kontroll over innboksen.
- [ ] Ved å implementere prinsippet om at ingenting flyttes fra innboksen med mindre det eksplisitt slettes eller flyttes til arkiv, forventer vi at brukerne vil oppleve en mer stabil og forutsigbar organisering av innholdet. Denne tilnærmingen antas å redusere risikoen for utilsiktet tap av informasjon og gi brukerne større kontroll over arkivering og sletting av innhold i innboksen.

Denne epicen bygger også på informasjon fra #111.

### Tasks
Contain all the issues needed to progress on the epic

```[tasklist]
### My tasks
- [x] Create test script and scenarios
- [ ] #124
- [ ] #126
```
### Definition of done
Denne epicen avsluttes når alle hypotesene er verifisert/avkreftet og design og funksjonalitet for oppgavebehandling er ferdigstilt.

**Comment by indiamaydesign** [comment]
### Hypotese
Outline the hypothesis
Quick summary of the research or foundation for this

### Overview
Explains the epic, description

### Tasks
Contain all the issues needed to progress on the epic

```[tasklist]
### My tasks
-  [ ] link to task
- [ ] or just create a task that doesn't need an issue
- [ ] or create a task and then choose to turn it into an issue
```
### Definition of done
What we need for this epic to be closed
