### ISSUE TITLE
Fundamental team structure / gameplan

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#2]
## Description
Reach full team allocation (internal and external) and ensure the team's ability to see the project through. 

## Additional information
Establish clarity in the team through a joint living document (gameplan). Include project description, team, roles, network and guidelines as well as success criteria, dependencies, challenges and goals, vision, gains and roadmap.

### Dependencies
No dependencies identified

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/1
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/3
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/4
```

**Comment by LisLonning** [comment]
### Overordnet beskrivelse

**Comment by sorensensig** [comment]
Closing epic as done.
