### ISSUE TITLE
Define scope, backlog and brief

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#3]
## Description
- Clarify project scope and what needs to be in place to ensure that the work moves in the right direction.
- Establish a clear brief that creates a joint understanding for the work internally and externally.
- Establish a clear backlog with milestones for the team to more easily measure progress and keep documentation in one place

## Tasks
```[tasklist]
### Initial gameplan tasks
- [x] Write project description
- [x] Map roles and resource needs
- [x] Create team rules
- [x] Establish project goals
- [x] Identify potential impact
- [x] Identify potential tasks / deliverables
- [x] Map success criteria, challenges and dependencies
```

```[tasklist]
### Initial scope tasks
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/68
```

```[tasklist]
### Initial backlog tasks
- [x] Create top-level issues in the Digdir roadmap
- [x] Establish milestones
- [x] Create and connect epics to each top-level issue
- [x] Create and connect initial issues required to complete each epic
```

**Comment by indiamaydesign** [comment]
Consider new gameplan (2.0) together:
- Goals
- Vision
- Dependencies
etc

**Comment by sorensensig** [comment]
Removed remainder of tasks from the epic as they represent iterative tasks or smaller administrative tasks that will be handled as we go and misrepresent the progress of the product team when left open.
