### ISSUE TITLE
Improve inbox, part A

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#306]
## Hypothesis
- Introducing too many changes might lead to confusion
- The transition should build on existing design 
- Improvements should utilise well-known design patterns and best practice

## Existing functionality to transition
- Inbox view
- Archive and delete dialogs
- Sharing a dialog
- Saved searches

## Suggested changes based on best-practice and well-known patterns
- Dialogs should open on a separate page (not just expand) to focus on a single task at a time
- Introducing a "draft" and "sent" folder to enable filtering out ongoing and completed tasks.

Dialog layout, list views and navigation:

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/305
- [ ] https://github.com/digdir/dialogporten-frontend/issues/142
- [ ] https://github.com/digdir/dialogporten-frontend/issues/146
- [ ] https://github.com/digdir/dialogporten-frontend/issues/326
- [ ] https://github.com/digdir/dialogporten-frontend/issues/324
- [ ] https://github.com/digdir/dialogporten-frontend/issues/407
- [ ] https://github.com/digdir/dialogporten-frontend/issues/328
```
