### ISSUE TITLE
Refaktorer CI/CD, release-piplines og versjonering

### ISSUE THREAD

**Issue by arealmaas** [digdir/dialogporten-frontend#308]
### Description

Ta inspirasjon av oppsettet i backend for å implementere dette i dialogporten-frontend. 

I hovedtrekk:
- Innfør endringer i bicep-struktur for å matche strukturen i backend-repo
- Innfør release-pipelines med release-please og ny GH actions-flyt

### Additional Information

- Skille ut arkitektur og applikasjonsdefinisjoner i egne mapper
- Legg gjenbrukbare moduler ut i egen `modules`-mappe
- Refaktorer github actions til å støtte nytt oppsett
- Innfør release please for automatisk tagging av releases og genering av changelogs
- Innfør release-pipeline til staging som matcher flyten i bildet nedenfor
![Image](https://github.com/digdir/dialogporten-frontend/assets/1777366/5c5f21fe-5e2a-4779-a4a9-b51a4eae5ae9)
- Slett gamle workflows (PublishTestFrontend, test-login, WorkflowTestFrontend)

```[tasklist]
### Tasks
- [x] Rydd opp i eksisterende workflows
- [x] Refaktorer bicep-struktur
- [x] Refaktorer GH workflows
- [x] Innfør release please og release-pipeline
- [x] Legg til application deployments
- [x] Fiks migration-job
- [x] Sett opp deploy til staging
```

**Comment by arealmaas** [comment]
haha, ser ut til å få samme issue med secrets her også som vi har for migration-joben i BE :) 

Har endelig fått satt opp et møte med Container Apps-teamet nå kl. 16:00 idag. Blir det siste jeg gjør før påske, så håper på no solid fix der 🌞🌞
