### ISSUE TITLE
Concept for inbox views and search results

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#326]
## Concept
- Inbox ("innboks") is a list of incoming dialogs sorted by date.
- Drafts ("utkast") is a list of dialogs representing ongoing, unfinished tasks
- Sent ("sendt") is a list of dialogs that has been completed, or is awaiting a response.
- Archive ("arkiv") is a list of dialogs that has been archived.
- Trash ("slettet") is a list of dialogs that has been marked for deletion, but has not been erased.
- Search results is an alternative view of the inbox ("Inbox" is selected in the sidebar). 
- All views uses a variation of the same list element.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/379
- [ ] https://github.com/digdir/dialogporten-frontend/issues/327
- [ ] Empty views/No hits
```

Figma: https://www.figma.com/file/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?type=design&node-id=1039-75540&mode=dev
