### ISSUE TITLE
Onboarding externals

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#4]
## Description
Create and execute plan for onboarding the external consultants.

## Tasks
```[tasklist]
### UI designer
- [x] Given appropriate accesses
- [x] Given introduction to the gameplan and relevant documentation
- [x] Given a fundamental understanding of Digdir, Altinn and the project
- [x] Invited to the kick-off event
```

```[tasklist]
### Front-end developer
- [x] Given appropriate accesses
- [x] Given introduction to the gameplan and relevant documentation
- [x] Given a fundamental understanding of Digdir, Altinn and the project
- [x] Invited to the kick-off event
```

```[tasklist]
### Service designer
- [x] Given appropriate accesses
- [x] Given introduction to the gameplan and relevant documentation
- [x] Given a fundamental understanding of Digdir, Altinn and the project
- [x] Invited to the kick-off event
```

```[tasklist]
### UX designer
- [x] Given appropriate accesses
- [x] Given introduction to the gameplan and relevant documentation
- [x] Given a fundamental understanding of Digdir, Altinn and the project
- [x] Invited to the kick-off event
```
