### ISSUE TITLE
Kartlegge 10 flyter for tjenestetilbydere 

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#409]
## Beskrivelse 
- Teamet trenger å kartlegge AS-IS flyter fra tjenestetilbydere med formål om å validere hvordan flytene passer til inn i de tekniske og designmessige rammene i arbeidsflate/dialgporten prosjektet. 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/416
- [ ] https://github.com/digdir/dialogporten-frontend/issues/419
- [ ] https://github.com/digdir/dialogporten-frontend/issues/418
- [ ] https://github.com/digdir/dialogporten-frontend/issues/127
- [ ] https://github.com/digdir/dialogporten-frontend/issues/1641
- [ ] https://github.com/digdir/dialogporten-frontend/issues/94
```

**Comment by AudunFK** [comment]
Lukkes - dekkes videre arbeid med mappingaktiviteter i Map Service Blueprints #760
