### ISSUE TITLE
Explore issues related to "shadow archives" building up over time

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#41]
## Background
An actor utilising Altinn's archive functionality have reported an issue related to "shadow archives" building up over time. There is a need for archival data to be stored for up to 2-3 months prior to being removed to ensure loss of data and that it remains available to the recipient. Archival data keeps growing in size due to difficulties deleting the elements where only one element can be deleted at one time. With an excess of 1200 elements coming in every month the actor faces a substantial task deleting every single element.

```[tasklist]
### Tasks
- [ ] Estimate ROI from number of affected service owners
- [ ] Discover archival needs and common workflows surrounding Altinn's archive product
- [ ] Define design alternatives
- [ ] Develop and test prototype
- [ ] Deliver solution
```
