### ISSUE TITLE
Insights and analysis - part 1

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#42]
## Description
Initial research and user involvement to map which needs the solution is meant to target and for which users.

## Tasks
```[tasklist]
### Research planning
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/44
```

```[tasklist]
### Conducting research
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/5
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/6
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/7
- [ ] https://github.com/digdir/dialogporten-frontend/issues/92
```

```[tasklist]
### Analysis
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/45
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/46
```

```[tasklist]
### Outcomes
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/11
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/26
```
