### ISSUE TITLE
Establish research plan for the discovery phase

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#44]
## Description

Crafting a clear research plan that helps define research goals and serve as a path ahead with identified key activities to enable alignment in the team and with stakeholders on the intended outcome of the research prior to commencing research activities. The core steps of the research plan will be laid out in Github as a means of transparency and tracking project progress.

## Additional Information
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/67
```

```[tasklist]
### Ideas for tasks
- [x] Talk with ABS re: what is in a form
- [x] Talk with service owners
- [ ] https://github.com/digdir/dialogporten-frontend/issues/92
```

**Comment by indiamaydesign** [comment]
- Get clarification on whether arbeidsflate with today's forms @sorensensig 
- Check if things like frist in today's solution have disappeared intentionally
