### ISSUE TITLE
Create a Load Balancer for BFF/FE in the test environment

### ISSUE THREAD

**Issue by arealmaas** [digdir/dialogporten-frontend#441]
### Description

We need a load balancer for the frontend and BFF. We could go for Traefik or a similar lb inside a Container App, but it would be more scalable, secure and decrease the maintenance need if we go for an Azure Application Gateway instead. An alternative here is Azure Front Door, but it's designed for global distribution which is something not relevant for us. Got that recommended from the Azure people as well.

https://learn.microsoft.com/en-us/azure/container-apps/waf-app-gateway

### Tasks

**Suggested solution**
- Create a new vnet that we can use for both the container app environment and the application gateway
- Create a Azure Application Gateway with two backend (frontend and BFF)

### Acceptance Criterias

- API should be available at `https://test.portal-pp.dialogporten.no/api`
- Frontend should be available at `https://test.portal-pp.dialogporten.no/api`
- Requests should be sent via the application gateway to the appropriate container app

```[tasklist]
### Tasks
- [x] Add vnet with subnets for container app env and application gateway
- [x] Add backends for bff and frontend with path based routing
- [x] Expose a public IP and connect it to the frontend IP of application gateway and add an A record in the DNS zone
- [x] Use the ssl certificate created for the domains
```
