### ISSUE TITLE
Forbedre søkefunksjonaliteten i Altinn innboks

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#442]
## Innsikt
[Lenke til analyse i Miro / Figjam](https://www.something.no)

```[tasklist]
### Issues / hypoteser
- [ ] https://github.com/digdir/dialogporten-frontend/issues/443
- [ ] https://github.com/digdir/dialogporten-frontend/issues/444
- [x] Som tenåring vil jeg bruke mobilen og diktere Siri til å skrive ord i søkefeltet for for å redusere stavefeil
- [x] Søket kan ha en auto-complete
```

```[tasklist]
### Tasks / sjekkliste
- [ ] https://github.com/digdir/dialogporten-frontend/issues/445
- [ ] Konseptualisere og skisse løsninger etter gjennomført brukerundersøkelse
```

```[tasklist]
### Issues
- [ ] Forbedre innboks
```

**Comment by LeifHelstad** [comment]
## Test
Denne ser jeg bort fra da det kan virke som den er lukket med feil "reason". Det tre lenkede issues er lukket med "Close as not planned". Da antar jeg at der er den riktige lukke-årsaken til denne parent-issue også.
