### ISSUE TITLE
eksempel

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#448]
## Designskisser
[Lenke til Figma-skisser](url)

```[tasklist]
### Tasks
- [ ] Skisser for desktop
- [ ] Skisser for ipad
- [ ] Skisser for mobil
```
