### ISSUE TITLE
Further develop dialogues and threads

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#487]
### Tasks
- [ ] Gjøre det tydeligere hvilke elementer som er klikkebare – og drøfte hvilke som skal være klikkebare?
- [ ] Som bruker vil jeg være trygg på at jeg har gjort alt jeg skal i dialogen
- [ ] Prinsippet for dialogtråder funker bra, men detaljer må på plass
- [ ] Jobbe med presise statuser; hva har vi teknisk mulighet til og hva skal de hete?
```
