### ISSUE TITLE
Map needs, existing insights and desk research

### ISSUE THREAD

**Issue by LisLonning** [digdir/dialogporten-frontend#5]
## Description
Gather and map previous research and reports that are relevant to the project as well as the gap where further research is necessary. 

## In scope
What's in scope for this analysis?

## Out of scope
What's out of scope for this analysis?

## Additional information
Links to relevant resources, documentation of other issues, UX sketches, technical architecture/requirements.

## Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/68
- [ ] https://github.com/digdir/dialogporten/issues/174
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/63
- [ ] https://github.com/digdir/dialogporten-frontend-react/issues/71
- [ ] https://github.com/digdir/dialogporten-frontend/issues/79
```

## Analysis
A description of how the analysis was done, what alternatives were considered etc

## Conclusion
What have we found out by doing this analysis
