### ISSUE TITLE
Deploy all services to Azure

### ISSUE THREAD

**Issue by arealmaas** [digdir/dialogporten-frontend#500]
### Description

Ensure all services is up and running in a test environment in Azure

### Acceptance Criterias

- Frontend and BFF should be hosted in Azure Container Apps with connections to postgresql and Azure Cache for Redis
```[tasklist]
### Tasks
- [x] Ensure all environment variabels and secrets are set for services
- [x] Set up hosting for Frontend and BFF
- [x] Ensure both bff and frontend is reachable as expected
- [x] Ensure that database is setup, and that the BFF can connect to it
- [x] Ensure that Redis is setup, and that the BFF can connect to it
```
