### ISSUE TITLE
Implement a detail view of inbox elements

### ISSUE THREAD

**Issue by elsand** [digdir/dialogporten-frontend#52]
## Description
**This issue spans the work required to implement a detail view of inbox elements in Arbeidsflate**

After performing av [list/search query](https://github.com/digdir/dialogporten-frontend/issues/53), the user should be able to click any given dialog and load its details view. These two combined form the basic functionality in Arbeidsflate.

The details view is loaded using the corresponding [API in Dialogporten to load a single dialog](https://dp-be-test-apim.azure-api.net/swagger/index.html#/Enduser/GetDialog). 

In the following sections, the non-obvious logic required for rendering the dialogue list is discussed/explained

### Authorization
The list view does basic authorization to see if the user has "read" access to the dialogs, but does not check whether or not any given action and/or dialog element is accessible. DIalogporten vil decorate any action or dialogElement with `isAuthorized: false` if the action or dialog element is not accessible. Information on _why_ access is not granted, and what roles/rights are needed to aquire access is not provided by Dialogporten, and will most likely not be provided by any Authorization-API either. Arbeidsflate will then have to decide whether or not the given action/dialogelement should be removed from view entirely, or just shaded/disabled. 

- [ ] Determine view logic for unauthorized actions and dialog elements

### Content
There are several types of content defined in a dialog; title, senders name, summary and "additional info". Only the latter is exclusively for the details view, and will contain up to 1024 characters of HTML. The HTML is restricted to simple formatting and lists, and may contain external links. This should be rendered verbatim to the user.

### Actions
Actions represent the things the user can do with the dialog at the present time. The actions contain a human-readable text in various languages, with links that the user should navigate to when the UI element representing the action is invoked (ie. button is clicked). Actions meant for GUI usage are separate from API actions - the latter are meant for custom SBS-es and should not be utilized by Arbeidsflate. The buttons contain a priority hint, which should affect how the UI element (ie. button) should be presented.

Actions can be write-actions, which should not cause a full browser redirect, but instead should invoke a client-side request performed with Fetch/XHR utilizing a special access token made available in the dialog. This feature relies on the feautures: https://github.com/digdir/dialogporten/issues/331 and https://github.com/digdir/dialogporten/issues/378 being implemented in Dialogporten.

Delete actions is a specialized form of write actions. These should invoke a DELETE request with the same token, and upon a successful response, immediately redirect the user back to the list view. The item should locally (as in local storage) be marked as hidden, pending it being actually marked as deleted in Dialogporten

See also https://digdir.github.io/dialogporten/#gui-handlinger

- [ ] Determine logic for handling success/error responses for write actions (see Subscribing to updates below)

Actions can also be associated with dialog elements. The semantics of which is up to the service owner to define, but it should be considered that UI elements for actions should be placed next or in some other way visually linked to the associated dialog element. This is particularly relevant for "front channel embeds" (see below).

- [ ] Determine who dialog element associations for actions should be handled 

### Dialog elements
Dialog elements are an abstraction describing arbitrary data pertaining to the dialog, usually in the form of attachments. Only dialog elements having links with consumerType: gui is to be consumed and rendered by Arbeidsflate. 

Dialog elements might be marked as "front channel embeds". Like write actions, this indicates that Arbeidsflate should perform a client side request (using the dialog token) to invoke the URL and render its contents like it would "additional info". It is however crucial that the response is parsed and sanitized before injecting into the DOM. Only a strict subset of HTML should be allowed; the subset defined in https://github.com/digdir/dialogporten/issues/30 should be sufficient.

Arbeidsflate must consider the content type-property when rendering; initially only "text/html" should be accepted. At some point we might expand this to support other content types (eg. "x-arbeidsflate/simple-form") which might incur other validation and rendering logic.

Arbeidsflate should gracefully handle any errors/timeouts invoking the remote endpoint and display a error message to the user.

- [ ] Determine logic for handling multiple front channel embeds

### Subscribing to updates
Dialogporten will support a [SignalR](https://dotnet.microsoft.com/en-us/apps/aspnet/signalr) based notification mechanism, making it possible for clients, using a dialogtoken for auth, to be notified whenever a dialog is updated, making it possible to trigger a reload at any point during which a dialog details page is opened.

This depends on https://github.com/digdir/dialogporten/issues/378

## Additional Information
* [Design elements in Figma](https://www.figma.com/file/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?type=design&node-id=8%3A85916&mode=design&t=pKjGP2R8EqnsaDn1-1)

## Tasks
```[tasklist]
- [ ] Implement BFF endpoint mapping requests/responses against Dialogporten details API with endusers token
- [ ] Implement SignalR client registering for refreshing the dialog when dialog changes occur
- [ ] Designimpl: title, summary, additional info
- [ ] Designimpl: simple actions (read actions causing full page navigations)
- [ ] Designimpl: write actions for delayed dialog updates (see https://digdir.github.io/dialogporten/#B13-L183)
- [ ] Designimpl: dialog elements (attachments)
- [ ] Designimpl: dialog elements (front channel embeds)
```

**Comment by LeifHelstad** [comment]
## Testplan

### Verifisere "Actions" slik de er implementert (1xx)
Test kontakter Dev for å få til verifisering i Staging miljøet.

### Har Transmissions tatt over for alt som er beskrevet for Dialog Elements (2xx)
Når Actions er bekreftet i 1xx kan for eksempel testen av om Actions i GUI er "tett nok" plassert UI-elementet Actionen gjelder gjøre via 2xx

### "Embeds" må avklares om de er implementert tilstrekkelig integrert i dialogen (3xx)
Knytningen mellom Actions og Embeds må klargjøres noe når det foreligger eksempler.

**Comment by LeifHelstad** [comment]
## Testrapport

🟢 funksjonalitet nevnt i #52 som ikke er spesifikt nevnt i denne siste oversikten har fungert ok under hele testforløpet
🟢 guiActions trigger som forventet, selv om ikke (den fake) service provider oppdaterer dialogen i gjeldene miljø
🟢 at ikke guiActions er implementert som en del av transmissions er OK. Det er ikke en forventing om dette.
🟢 at ikke contentReference for Transmissions rendres i Arbeidsflate følges opp separat via #1707

Basert på dette
