### ISSUE TITLE
Implement list view of inbox elements

### ISSUE THREAD

**Issue by elsand** [digdir/dialogporten-frontend#53]
## Description
**This issue spans the work required for the basic implementation and setup of the list/search view.** 

The list/search view is probably the most central part of "arbeidsflate", where the users are to find the dialogs that are most important to them. This is achived by performing various [search queries to Dialogporten](https://dp-be-test-apim.azure-api.net/swagger/index.html#/Enduser/GetDialogList), and applying view logic to them.

This issue also entails setting up the basic communication wiring between the static React frontend, and the BFF which keeps track of sessions and access tokens that are used against Dialogporten, mapping DTOs between the frontend and Dialogporten API models.

In the following sections, the non-obvious logic required for rendering the dialogue list is discussed/explained

### Logic for selecting view

Dialogporten dialogs have a status-field that indicates what stage it is in. These are currently:
 - New 
 - InProgress
 - Waiting
 - Signing
 - Cancelled
 - Completed

The service owner will have complete control on what status is set at all times. Arbeidsflate will have to use this in order to properly place the item into the correct view.

* If status is Waiting, it should be in the "Sendt" view
* If status is Cancelled, it should be in the "Slettet" view
* If status is New, it should be in the "Inbox" view

Only dialogs with "InProgress" status should be in the "Utkast" view. However, there are states in which the dialog should be moved to back the "Inbox" view, despite bing "InProgress" - eg. when the service owner adds a dialog element/changes the content/adds an activity for an item that's "InProgress" - typically for some sort of preliminary feedback. A "natural" heuristic here would be to place in "Inbox" all dialogs in which the last activity in the activity log originated from a service owner.

- [ ] Decide on logic/heuristic for view selection

### Seen logic

The dialog search DTO will contain an [excerpt of the activity list](https://github.com/digdir/dialogporten/issues/370) and there will be information in there which will [indicate if the user has seen the dialog in its current state](https://github.com/digdir/dialogporten/issues/203). This information should be used to toggle any "(not) seen by be" design logic. There will also be information on who others (if any) has seen the dialog.

We need to determine if bolded/other visual indicators of the dialog being "unseen" should be whether or not it is not seen by _you_ or not seen by _anyone_. The first option will entail, giving the logic/heuristic for view selection above, that any given user may experience "unseen" dialogs in the view "Utkast".

- [ ] Decide on logic/heuristic for seen/unseen visual indication

### From/to logic

There is no explicit information in the dialog with information on whether or not a dialog is in a "from" or "to" state, but this will necessarily follow the logic for view selection like stated above (Innboks = from serviceowner, Utkast = from party, Sendt = from party)

There name of the party for the given dialog is not given by Dialogporten, and will need to be looked up. This will rely on https://github.com/digdir/dialogporten/issues/321 being implemented.

## Additional Information

* [Design elements in Figma](https://www.figma.com/file/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?type=design&node-id=8%3A85916&mode=design&t=pKjGP2R8EqnsaDn1-1)
* Depends on Dialogporten-features delivered in https://github.com/digdir/dialogporten/issues/370

## Tasks

```[tasklist]
- [ ] Implement BFF endpoint mapping requests/responses against Dialogporten search API with endusers token
- [ ] Implement logic for selecting view (innbox, drafts, sent)
- [ ] Implement logic for seen/not seen
- [ ] Implement lookup of party name for "from/to" (needs https://github.com/digdir/dialogporten/issues/321)
- [ ] Designimpl: Title and summary
- [ ] Designimpl: "From" and "to" labels
- [ ] Designimpl: "Sett av"-text
- [ ] Designimpl: Number of attachments
- [ ] Designimpl: Progress-percentage
```

**Comment by LeifHelstad** [comment]
## Testdata

To sett med bruker og dialoger som kan sjekkes for status:
**19905895985**
- 	Har 4 i innboks hvorav 2 uleste
- 	Har 2 i Utkast
- 	Har 1 i Sendt

**14886498226**
- 	Har 33 uleste i innboks
- 	Har 1 i Arkiv
- 	Har 2 i Papirkurv

**Comment by LeifHelstad** [comment]
## Test 2

TC-300
I denne testen slettes en dialog ved hjelp av en guAction.

TD-300
"party": "urn:altinn:person:identifier-no:12907499179"
Test av sletting, Dialog A
	01949244-56f5-75b1-bcf5-d9a28e9baac8
Test av sletting, Dialog B
	01949244-e6e0-70f5-97ab-8e441f421206

AR-300

![Image](https://github.com/user-attachments/assets/83b3bf77-ac85-4d03-a596-ed427ceac504)

TC-301
Inne på "Dialog A" trykkes guiAction "Slett melding"
ER-301
Knappetrykket gjør at dialogporten-service-provider oppdaterer dialog 01949244-56f5-75b1-bcf5-d9a28e9baac8 slik at den for EndUser skal oppfattes som slettet.

AR-301
Dialog A er

**Comment by LeifHelstad** [comment]
## Testresultater
AR-100
            "id": "01922e2b-0f4a-7267-8b7c-31c469f821ec",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 0,
            "createdAt": "2024-02-14T23:00:00.0000000Z",
            "updatedAt": "2024-02-14T23:00:00.0000000Z",
            "status": "Draft",

            "id": "01922e2b-16ce-71ee-9486-73dc3fb7ad27",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 1,
            "createdAt": "2024-01-06T11:15:00.0000000Z",
            "updatedAt": "2024-01-15T14:24:00.0000000Z",
            "status": "Completed",

            "id": "01922e2b-1957-7104-a649-aec798fe9508",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 1,
            "createdAt": "2023-12-23T23:00:00.0000000Z",
            "updatedAt": "2023-12-25T11:34:00.0000000Z",
            "status": "RequiresAttention",

            "id": "01922e2b-1812-7537-b092-b86338f1b3cb",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 0,
            "createdAt": "2023-07-10T22:00:00.0000000Z",
            "updatedAt": "2023-07-18T10:35:00.0000000Z",
            "status": "InProgress",

            "id": "01922e2b-13d3-723f-afde-57932a3d0e44",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 0,
            "createdAt": "2023-07-10T22:00:00.0000000Z",
            "updatedAt": "2023-07-10T22:00:00.0000000Z",
            "status": "Draft",

            "id": "01922e2b-1243-7190-948e-e821518b20f5",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 1,
            "createdAt": "2023-07-10T22:00:00.0000000Z",
            "updatedAt": "2023-07-11T22:00:00.0000000Z",
            "status": "Sent",

            "id": "01922e2b-10f4-77e9-b08c-09df3ba65fd4",
            "org": "digdir",
            "serviceResource": "urn:altinn:resource:super-simple-service",
            "serviceResourceType": "genericaccessresource",
            "party": "urn:altinn:person:identifier-no:19905895985",
            "guiAttachmentCount": 1,
            "createdAt": "2023-07-10T22:00:00.0000000Z",
            "updatedAt": "2023-08-04T22:00:00.0000000Z",
            "status": "Completed",

**Comment by LeifHelstad** [comment]
## Testrapport

Basert på det som er observert så er prinsippene om at dialogene kan ha ulike statuser og at disse påvirker visning implementert.
Om en dialog er lest eller ikke påvirker også visning som beskrevet.

#53 lukkes som levert med teststatus passed.

## Observasjoner

Det er observert at: 
- noen av statusene ikke legger seg i det view som er nevnt
- status Completed har ikke noe view i det heletatt
- det er flere statuser nå enn de som ble listet som kjent i juni 2023 når saken ble opprettet

Design har ikke landet helt hvilke State+Seen som skal plassere dialogen i hvilket view.
Ut i fra observasjonene opprettes en ny Story for å definere en matrise som gir en samlet oversikt over dette.
