### ISSUE TITLE
Users need to be able to find and understand dialogs on mobile

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#544]
## Dialogs

Do users understand dialogs on mobile? 

## Analyze Guerilla User Test 1 and 2:
https://www.figma.com/board/kKAYWOv5q5seHV3dK1iKaV/Sammendrag-fra-intervjuer-og-funn?node-id=1911-6548&t=pk5BvSl7V3dwN7Ce-4

## Basic functionality

Do they understand functionality like search and filtering? 

## Navigation

Do users manage to navigate using global navigation?

```[tasklist]
### Tasks
- [x] Do users find the dialog they were notified about?
- [x] Do they manage to find an older dialog? (Using search, filters, navigation, etc.)
- [x] Do they understand the process of a dialog? (What has happened, when, by whom?
- [x] Do users understand the different types of dialogs, statuses etc.
- [ ] Do users understand search and filtering?
- [ ] Do users understand bulk actions on mobile?
- [ ] Do users understand global navigation?
```
