### ISSUE TITLE
Prepare usability tests with company users (including municipalities)

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#546]
## Notes
- Fokus på dialoger for proffbrukere, finne og forstå. (Søk/filtrering)​
- Scenarioer på tvers av aktører, underenheter.

## Link to preparation board Figjam:
https://www.figma.com/board/kKAYWOv5q5seHV3dK1iKaV/Sammendrag-fra-intervjuer-og-funn?node-id=1975-7573&t=SkXqZKr7VAwm2zs1-4

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/629
- [x] Create test scenarios for company users
- [x] Recruit test users
- [x] Conceptualize functionality for this user test
```
