### ISSUE TITLE
Kompleksdialog - oversette Dialog-data til innhold i InboxItem

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#571]
![Image](https://github.com/digdir/dialogporten-frontend/assets/3768832/802c9d84-3670-4da3-bf71-32c85d49c041)

Komplett data for bruker 14886498226 er i dev, dialogId 9c668f01-35fb-d676-82c0-97cf3e6be8a4

1. hente data nødvendig for gql
2. berike UI med data
3. komponenter som mangler for å vise UI må ev lages og utføres som separate oppgaver
```[tasklist]
### Tasks
- [x] https://github.com/digdir/dialogporten-frontend/issues/575
- [x] https://github.com/digdir/dialogporten-frontend/issues/576
- [x] https://github.com/digdir/dialogporten-frontend/issues/580
- [x] https://github.com/digdir/dialogporten-frontend/issues/602
```
