### ISSUE TITLE
As a leader I want a better overview of sick leave linked to a employee

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#577]
## Insight and documentation:
- Link to Figma sketches and screenshots of sick leave and dialogues from Nav: https://www.figma.com/design/S4RwqVs8N0PzeotMTeXIwe/Innboks-UI?node-id=2843%3A3843&t=6Ekv0tugKYJXjUgB-1
- 

```[tasklist]
### Tasks
- [x] Carry out user research to map pain points and needs related to a better overview in Inbox
- [x] User interview (no 2) to map gaps and whether there are more pain points and ways a professional users receive sick leave and how this is presented
- [x] Document screenshots and insights from Nav's user interface associated with sick leave
- [x] Analyze user needs and pain points and document new potential hypotheses
- [ ] https://github.com/digdir/dialogporten-frontend/issues/638
```
