### ISSUE TITLE
Document all existing UI for development

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#579]
```[tasklist]
### Tasks
- [x] Update UI with changes and iterations after guerilla tests.
- [x] Document all exisiting UI in Figma
- [x] Document primary interactons and flows
- [x] Present and execute UI demo
```

```[tasklist]
### Pages/views
- [x] Dialog page (mobile + desktop)
- [x] Inbox, drafts and sent (mobile + desktop)
- [x] Archive and trash (mobile + desktop)
- [x] Search, filter, sort (mobile + desktop)
- [x] Switch account (mobile + desktop)
- [x] Bulkmode (mobile + desktop)
- [x] Saved searches (mobile + desktop)
```
