### ISSUE TITLE
Go through issue #474, #449, #545, #554 to ensure everything is done and identify potensial new issues / hypothesis

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#582]
## Link to Hypothesis tree:
https://www.figma.com/board/kKAYWOv5q5seHV3dK1iKaV/Sammendrag-fra-intervjuer-og-funn?node-id=1975-7573&t=pk5BvSl7V3dwN7Ce-4

## Link to analyze board of Guerilla test 1 and 2:
https://www.figma.com/board/kKAYWOv5q5seHV3dK1iKaV/Sammendrag-fra-intervjuer-og-funn?node-id=1911-6548&t=pk5BvSl7V3dwN7Ce-4

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/474
- [ ] https://github.com/digdir/dialogporten-frontend/issues/449
- [ ] https://github.com/digdir/dialogporten-frontend/issues/545
- [ ] https://github.com/digdir/dialogporten-frontend/issues/554
```
