### ISSUE TITLE
Set up staging environment for Arbeidsflate

### ISSUE THREAD

**Issue by arealmaas** [digdir/dialogporten-frontend#619]
Set up a staging environment on the domain: `af.tt.altinn.no` 
```[tasklist]
### Tasks
- [x] Set up release pipeline towards Staging
- [x] Merge release PR
- [x] Set up domain af.tt.altinn.no
```

**Comment by arealmaas** [comment]
Currently blocked by https://github.com/digdir/dialogporten/issues/783
