### ISSUE TITLE
Map today's user interface

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#63]
Map Altinn Inbox of today and earlier sketches.
📎 [Desk research Figma file](https://www.figma.com/file/OnZhfn8oNnOgl6rs5WvDJL/Kartlegging%2C-dagens-innboks?type=design&mode=design&t=vMGl6ukH0wcangLV-0) (requires Digdir login)

Findings and summary:
📎 [Link to presentation](https://www.figma.com/proto/OnZhfn8oNnOgl6rs5WvDJL/Kartlegging%2C-dagens-innboks?type=design&node-id=307-19171&t=7odabWZKBoiBvD9z-0&scaling=contain&page-id=271%3A16053)

### Tasks
What we did:

```[tasklist]
### Tasks
- [x] Look up earlier conceptual work on "proff innboks"
- [x] Look up earlier sketches on related projects
- [x] Look up other inboxes to identify patterns and best practice
- [x] Get a basic overview of relevant APIs to understand data flows
- [x] Look up and document best practice for similar interfaces.
```

### Findings
Navigation and ui patterns:
- Navigating between inbox, archive, trash and search uses an unfamiliar pattern with layout and color changes.
- Navigating to a single dialog uses an unfamiliar pattern where a single dialog is expanded inline.
- Some functions like "share" and "activity log", uses an unfamiliar pattern for modals, animated from the right, detached from the content that triggered it. 

Navigation and ui patterns, best practice:
- Inbox, Archive, Trash and Search uses the same or similar views. 
- Navigating to a single dialog focuses on that spesific dialog.
- Simple functions uses simple ui patterns. Modals are displayed in an overlay above the content that triggered it. 

Search and filtering:
- Search is a prominent part of the UI, but does not work as expected.
- Only titles are indexed, giving limited hits.
- Filters are hidden from view and is only available for pre-filtering (before searching), which might result in zero hits.
- Words are not highlighted in search results.
- Search result view is detached from the rest of the inbox.

Search and filtering, best practice:
- All content is indexed, giving better results.
- Suggested or recent searches are displayed as you type.
- Pre-filtering is hidden, but relevant post-filters are displayed along with the results.
- Words are highlighted in search results.
- Search results uses the same view as other listings.

Listings:
- List elements are hard to distinguish from one another. 
- Titles are often poor. No description or body. 
- Date/time (created/changed) is not displayed in list elements.
- Sender could be clearer. Recipient is not displayed.
- Unclear who has seen/opened the dialog (Shared inboxes)
- Meaning of icons and colors are unclear. 
- Title prefix indicating type of message does not add any value.
- Core inbox functions (move to archive/trash, mark as read/unread) change depending on dialogs.
- Bulk operations are not available.

Inbox listings, best practice.
- Sender, recipient and timestamp.
- Title and extract of body.
- Connected items are displayed in threads.
- Read/unread are clearly distinguished.
- Core inbox functions is part of the surrounding interface and have a fixed location.
- Bulk operations are available in all list views.

### Early design ideas
Quick mockup of a possible list view with bulk operations:

![BulkList](https://github.com/digdir/dialogporten-frontend/assets/1138656/d8d86664-14e9-4332-963b-1aa05ad5bb34)

### Next steps
What next tasks, what to do from here

- Explore alternative layout options that follow well-known, more established UI patterns, to make it easier to navigate and understand the inbox. #78 
- Explore different designs for list elements and dialogs that make it easier to understand what the dialog is about and what action you need to do. #78 
- Work on improving search functionality to enable better results.
- Work with service owners to create better content.
