### ISSUE TITLE
Sketch concepts for a better overview of sick leave in inbox related to an employee

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#638]
```[tasklist]
### Tasks
- [x] Sketch different concepts based on research and mapping
- [ ] Choose concept for testing
- [ ] Analyze results and user needs from user test
- [ ] Document finding
```
