### ISSUE TITLE
Prepare legal documents prior to research

### ISSUE THREAD

**Issue by sorensensig** [digdir/dialogporten-frontend#67]
## Description
Before research can commence we are required to follow a few legal guidelines listed as tasks below.
To be better positioned to finish the tasks below, it is recommended that a rough draft of the research plan have been created first. It is important for us to know who we are going to talk to and which data we will process in addition to which methods we will use.

## Tasks
```[tasklist]
### Tasks
- [x] Finalise and sign data processor agreements
- [x] Conduct a privacy assessment ([link](https://digdir.sharepoint.com/:w:/s/Prosjekt_DialogportenArbeidsflate/ERYR73vg4XBCvVxH6YYHkP4B-mnvQUSEFcn54d8kSRYKSg?e=cVd0TU))
- [x] Create consent form(s) ([link](https://www.figma.com/file/cWURTftoc1fvXBzrEsIW7sza/Maler-og-ressurser?type=design&node-id=1854:7892&mode=design&t=rxMirp2BG7oCHd7V-1))
- [ ] Get final versions approved
- [ ] Create locked teams folder for files
```
Databehandleravtaler håndteres i issue [https://github.com/Altinn/altinn-juridisk/issues/156](url)

**Comment by sorensensig** [comment]
@benedicteos har dere fått noen status på databehandleravtalene enda?

**Comment by benedicteos** [comment]
@sorensensig - nei ikke hørt noe fra Innkjøp etter jeg oversendte alle avtalene til signering forrige uke. Skal purre!

**Comment by benedicteos** [comment]
https://github.com/Altinn/altinn-juridisk/issues/156

Oppgave knyttet til databehandleravtaler håndteres i private repo team juridisk

**Comment by benedicteos** [comment]
@sorensensig databehandleravtaler for tre konsulenter er signert.

**Comment by sorensensig** [comment]
Kjempeflott, takk for hjelpen @benedicteos!

**Comment by indiamaydesign** [comment]
Version finished for initial design research tasks. Must reach out to legal again for final versions that can become the new template for other teams.
