### ISSUE TITLE
Clean-up of issues and tasks in Github design board / Figjam board

### ISSUE THREAD

**Issue by krteige** [digdir/dialogporten-frontend#686]
```[tasklist]
### Tasks
- [x] Create a task list for the "summer jog" sprint
- [x] Assign issues if relevant
- [ ] Book session for joint clean-up
```
