### ISSUE TITLE
Knapp: Sortere data

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#698]
Legge til knapp i de ulike dialogvisningene for å kunne sortere dialoger etter et valgt kriterie.

![Image](https://github.com/digdir/dialogporten-frontend/assets/3768832/3bd1e382-1026-4159-8672-bdc96947ab65)

Knappen åpner en liste over listelementer (lik som FilterListItems) over kriterier som dialogene kan sorteres etter, der default er sist oppdatert. Sortering bør fremgå i url.

```[tasklist]
### Tasks
- [x] Kontekst-meny (dropdown) fra FilterBar bør gjenbrukes til å brukes for valg av sortering
- [x] Vise sorteringsvalg i dropdown
- [ ] Sortere data etter valgt sorteringskriterium
```
