### ISSUE TITLE
Establish AS-IS customer journey of the Altinn Inbox

### ISSUE THREAD

**Issue by AudunFK** [digdir/dialogporten-frontend#70]
### Description

Understand the AS-IS customer journey for the current Altinn inbox solution

### Tasks

- [x] - Map out the AS-IS user journey 
- [x] - Understand the current painpoints
- [ ] - Talk to stakeholders to get a better understanding of the current inbox solution
- [ ] - Validate findings with stakeholders 
- [ ] - Map out the journey of dialogs in the current inbox solution

**Comment by sorensensig** [comment]
Evaluated to have limited value - closing issue.
