### ISSUE TITLE
Make plan for design activities by understanding focus area for Arbeidsflate and current inbox situation

### ISSUE THREAD

**Issue by Hamyng** [digdir/dialogporten-frontend#71]
### Description

Discuss focus area

### Tasks

- [x] Find out if it is valuable to visually map out current inbox situation
- [x] Find out if it is valuable to focus on improving design elements in Altinn inbox for the first iteration
- [x] Create presentation to present findings in regards to activities, focus area and future work
