### ISSUE TITLE
Gruppere og hente SearchDialogs fra samme liste i oversikten over dialoger

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#729]
Datakilden for dialoger som vises i hvert view (inbox, sendte og under arbeid) er spredt til å være søkeresultater (såkalte "søketreff"), view-spesfikke (p.t. alle dialoger filtrert på `status`), og eller filtrert og/eller sortert oversikt over alle elementer. 

Ref. todo:
```
/*
      Todo: There are now many competing lists for dialogs as data source for the output of this component. This needs to be cleaned up.
      items, searchResults, filteredDialogsForView, dialogsForView, dialogs, ...
      Search should include filters, update of filters should refetch search results.
   */
```

Kriteriene for visning, f.eks. dersom det er resultater av et søk og/eller filtrert og filtrert liste, henger tett sammen med hvordan disse elementene skal grupperes i visningen:

- Elementer som er sortert på dato (eneste p.t.) bør grupperes etter hensiktsmessig fellesnevnes, f.eks. år eller måneder. 
- Ved søk, er det kun søkeresultater som bør vises som én gruppe med passende tittel per "view".
- Ved filtrering, "treff i <view". 

```[tasklist]
### Tasks
- [x] Støtte dynamisk gruppering av data med egendefinerte labels
- [x] Visning av oversikt over dialoger bør hentes fra samme liste, uavhengig av filter, sortering og/eller om det er søketreff
- [x] Utifra kriteriene for grupper, angi riktig grupper inger(og med riktig data) ved søk/filter/sortering
```
