### ISSUE TITLE
Presentasjon brukertester proffbruker

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#759]
```[tasklist]
### Tasks
- [x] Lage v1 og gjennomgå med teamet og få tilbakemeldinger
- [x] Itere / endre med tanke på ulike mottakere / presentasjoner v1.1
- [x] Få inn skjermbilder i presentasjonen
- [x] Lage en versjon for Skatt og dele resultatene med samarbeidsteamet
- [x] Lage en versjon for interne
- [x] Legge på teams og dele med teamet
```

**Comment by LeifHelstad** [comment]
## Test
Oppfatter dette som design-task og ikke produktendringer som kan testes.
