### ISSUE TITLE
Explore layout and design options

### ISSUE THREAD

**Issue by ingefossland** [digdir/dialogporten-frontend#78]
Explore alternative layout options that follow well-known, more established UI patterns, to make it easier to navigate and understand the inbox.

Explore different designs options for list elements and dialogs that make it easier to understand what the dialog is about and what action need to be done.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten-frontend/issues/110
- [ ] https://github.com/digdir/dialogporten-frontend/issues/111
- [x] https://github.com/digdir/dialogporten-frontend/issues/112
- [ ] https://github.com/digdir/dialogporten-frontend/issues/113
```

**Comment by indiamaydesign** [comment]
Remaining issues and tasks have been moved to new epics in the design board.
