### ISSUE TITLE
PartyDropdown: Add subparties to the dropdown + grouping 

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#881]
Jf. @ingefossland kommentar nedenfor. 
```[tasklist]
### Tasks
- [x] Refactor logic for merging subparties and use in both PartyDropdown and global menu
- [x] Align design so that both Partydropdown and global menu uses the same design
- [x] Create section page grouping by people and organisations
```

**Comment by ingefossland** [comment]
Om jeg forstår problemstillingen riktig trenger dere skisser på aktørvalg med hoved- og underenheter? 

Forslaget er å slå dem sammen og behandle dem helt likt. Dvs:

1. Der hoved- og underenhet har like navn vises kun hovedenhet. Alle dialoger fra hoved- og underenhet vises samlet.
2. Der hoved- og underenhet har ulike navn (f.eks. Oslo kommune vs. Bydel Frogner) vises både hovedenhet og underenheter, men det gjøres ikke noe visuelt skille mellom hoved- og underenhet. På hovedenhet vises alle dialoger fra hoved- og underenheter, og man kan filtrere på underenheter ("mottaker" i skissene). 

Hypotesen er at skillet mellom hoved- og underenheter er forvirrende og fører til unødvendig kompleksitet. Små selskaper har ikke noe forhold til underenheten, og i større organisasjoner kan det variere hvor ting sendes. Ved å samle dialogene på øverste nivå i hierarkiet unngår vi at brukere overser dialoger som er sendt til underenheter. 

Når det gjelder gruppering må vi i første omgang videreføre "favoritter" fra dagens løsning, skisser kommer.

**Comment by seanes** [comment]
Gjelder også global rollevelger.

**Comment by seanes** [comment]
Oppgaven utvides med gruppering

![image](https://github.com/user-attachments/assets/f6796c33-89af-447f-8ff0-6fbf15dbf43e)
