### ISSUE TITLE
UI: ferdigsstille layout / aligne med prototype

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#926]
Implementerer et par diskrepanser i designet, slik at det er mer i tråd med figma/prototypen som ble overlevert av design ved designfrys.

```[tasklist]
### Tasks
- [x] Header
- [x] Layout for sidebar
- [x] Meny brukt av sidebar: riktig bakgrunnsfarger for ikoner og hover, riktig line-height / row-gap
- [x] Footer
- [x] Font-størrelser og -vekt på h1, h2 .... og p
```

**Comment by seanes** [comment]
Jeg tror denne er ferdig nå @alexdigdir, så foreslår at vi setter den i review.
