### ISSUE TITLE
Case: Skatteetaten

### ISSUE THREAD

**Issue by indiamaydesign** [digdir/dialogporten-frontend#94]
### Description

Find a service in the top 50 services that can be the foundation for a pilot with the new inbox.

Considerations - do we need to consider private and business users? Would this be two different services or one service?

```[tasklist]
### Tasks
- [x] Hold workshop with Skatteetaten on survey data and apply to pilot service ideas
- [x] Talk with ABS to find the top candidates in terms of most requests for help with specific services etc
- [x] Prep design team for workshop (before christmas)
- [x] Choose service to represent with Skatteetaten
- [x] Hold working day with Skatteetaten to map out a service
```

**Comment by indiamaydesign** [comment]
Waiting to hear back from ABS re: suggested services, why etc
