### ISSUE TITLE
Translate all hypotheses into user stories for functional testing

### ISSUE THREAD

**Issue by theresaharmanen** [digdir/dialogporten-frontend#985]
Supporting Naila Raza with documentation and presentations that she might need in order to plan and run functional tests.

https://www.figma.com/board/kKAYWOv5q5seHV3dK1iKaV/Sammendrag-fra-intervjuer-og-funn?node-id=2789-12832&t=yWEYO3Di8X3kyu9O-1

```[tasklist]
### Tasks
- [x] Make a template for User stories and acceptance criteria
- [x] Present the template for the team and adjust
- [x] Translate every hypothesis to epics and user stories
```
